/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ufps.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import ufps.controlador.controlador;

/**
 *
 * @author Jesus
 */
public class JFchat extends javax.swing.JFrame {

    /**
     * Creates new form chat
     */
    private controlador cont;
    private String nombre;
    private String historial="";
    private ArrayList<String> historialPri=new ArrayList<String>();
    private JFchat chat;
    private JFchatPriv priva;
    

     
     
     
     
    public JFchat(String nombre) {
        this.nombre=nombre;
        
        initComponents();
        this.txtname.setText("Usuario:"+""+nombre);
        this.PaneEditor.setLayout(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jpConectados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtEnviar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCombo = new javax.swing.JComboBox();
        btbTodos = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        txtname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaneEditor = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(32, 29, 26));
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setVisible(true);

        jpConectados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Conectados:");

        javax.swing.GroupLayout jpConectadosLayout = new javax.swing.GroupLayout(jpConectados);
        jpConectados.setLayout(jpConectadosLayout);
        jpConectadosLayout.setHorizontalGroup(
            jpConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConectadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jpConectadosLayout.setVerticalGroup(
            jpConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConectadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        btbTodos.setText("Enviar a Todos");
        btbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbTodosActionPerformed(evt);
            }
        });

        jButton2.setText("Dictado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombo, 0, 403, Short.MAX_VALUE)
                    .addComponent(txtEnviar))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btbTodos)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        txtname.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ufps/imagenes/user_icon-icons.com_57997.png"))); // NOI18N

        PaneEditor.setEditable(false);
        PaneEditor.setContentType("text/html"); // NOI18N
        PaneEditor.setAutoscrolls(false);
        jScrollPane1.setViewportView(PaneEditor);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jpConectados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpConectados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensaje=this.txtEnviar.getText();
        String nombre=(String)this.jCombo.getSelectedItem();
        this.historial+=estilo.htmlEnviado(mensaje);
        this.cont.enviarMensaje(mensaje, nombre);
        this.PaneEditor.setText(historial);
        this.txtEnviar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbTodosActionPerformed
        // TODO add your handling code here:
        String mensa=this.txtEnviar.getText();
        String mensaje="(Mensaje a Todos)"+this.nombre+":"+""+mensa+"\n";
        this.historial+=estilo.htmlEnviado(mensaje);
        this.cont.enviarMensajeTodos(mensaje);       
        this.PaneEditor.setText(historial);
        this.txtEnviar.setText("");
        
    }//GEN-LAST:event_btbTodosActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

public void ingresarMensaje(String cad){
   this.historial+=estilo.htmlRecibido(cad);
   this.PaneEditor.setText(historial);
    System.out.println(historial);
}

public void ingresarMensajePrivado(String cad){
  
   this.priva.recibirMensaje(cad);
}

public void mensajePrivado(String cad,String nom){
    this.cont.enviarMensajeP(cad, nom);
}

public boolean isNull(){
    if(priva==null)
        return true;
    return false; 
    
}
public void mostraConectados(String cad){
    String []list=cad.split(",");
    String aux="Conectados"+"\n"+cad;
    JButton [] lbl=new JButton[list.length];
    this.setLayout(null);
   this.jCombo.removeAllItems();
    this.jpConectados.removeAll();
   this.jpConectados.add(this.jLabel3); 
   this.chat=this;
    int x=30;    
    for (int i = 0; i <list.length; i++){
         String usuario=list[i];
         ImageIcon img= new ImageIcon(getClass().getResource("../imagenes/online.png"));         
         lbl[i]=new JButton(img);
         lbl[i].setText(list[i]);
         lbl[i].setBounds(10, x, 120, 40);
         lbl[i].addActionListener( new ActionListener() {

             @Override
             public void actionPerformed(ActionEvent e) {
                 priva=new JFchatPriv(chat,usuario);
                 priva.setVisible(true);
                
             }
         }
         );
         x=x+45;
         String cade=usuario+":::";
         this.getHistorialPri().add(cade);
       
         
         
         this.jpConectados.add(lbl[i]);
        if(!list[i].equals(nombre)){
        this.jCombo.addItem(list[i]);
        
        }
        
    }
   this.jpConectados.repaint();
    System.out.println(cad);
       
    
     

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane PaneEditor;
    private javax.swing.JToggleButton btbTodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCombo;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpConectados;
    private javax.swing.JTextField txtEnviar;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @param cont the cont to set
     */
    public void setCont(controlador cont) {
        this.cont = cont;
    }

    /**
     * @return the historialPri
     */
    public ArrayList<String> getHistorialPri() {
        return historialPri;
    }

    /**
     * @param historialPri the historialPri to set
     */
    public void setHistorialPri(ArrayList<String> historialPri) {
        this.historialPri = historialPri;
    }
}
